name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls -a
      - run: docker-compose up
      - run: docker-compose exec php bin/phpunit
